# Generated by Django 3.1.4 on 2021-05-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=999, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
