# Generated by Django 3.1.4 on 2021-05-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pagehit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
