# Generated by Django 3.1.4 on 2021-05-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_recentbbs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentbbs',
            options={'ordering': ['-attended_at']},
        ),
    ]
