# Generated by Django 3.1.4 on 2021-05-26 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210526_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteBb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-liked_at'],
            },
        ),
    ]
