# Generated by Django 3.1.4 on 2021-05-26 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_favoritebb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='likes',
            field=models.ManyToManyField(related_name='bb_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FavoriteBb',
        ),
    ]
