# Generated by Django 3.1.4 on 2021-06-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210526_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='send_messages',
            field=models.BooleanField(default=True, verbose_name='Разрешить сообщения'),
        ),
    ]
