# Generated by Django 3.1.4 on 2021-06-02 08:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210602_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
