# Generated by Django 3.2.5 on 2021-07-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_bb_likes_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ['order', 'name']},
        ),
    ]
